# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kzz_HacxxpkMic7TtnmKYCvBPURW8S5u
"""

#Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.

v = False

while v == False:
  nota = float(input("Coloque uma nota entre zero e dez:"))
  if nota >= 0 and nota <= 9:
    v = True
    print("Valor válido")
  else:
    print("Inválido. Tente novamente")

#Faça um programa que calcule o mostre a média aritmética de N notas.

soma = 0

for i in range(5):
  nota = float(input("Coloque sua nota:"))
  soma += nota
  media = soma / 5
print(f"A soma é:", soma)
print(f"A média é",media)

#Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
#pedir as informações.

f = False
v = True

while f == False:
  nome = input("Usuário:")
  senha = input("Senha:")
  if senha == nome:
    v = False
    print("Erro.")

  elif nome != senha:
    v = True
    print(f"Certo.")
    break

#Um funcionário de uma empresa recebe aumento salarial anualmente. Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
#1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
#percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
#salário inicial do funcionário.

salario = float(input("Digite seu salário: "))
ano = 1995
ano_atual = int(input("Ano atual: "))
aumento = 1.5 / 100

while ano < ano_atual:
  ano += 1
  salario *= 1 + aumento
  aumento *= 2
  print(f"O salário em {ano} é de {salario:.2f} reais")

#Faça um programa que leia e valide as seguintes informações:
# Nome: maior que 3 caracteres;
# Idade: entre 0 e 150;
# Salário: maior que zero;
# Sexo: 'f' ou 'm';
# Estado Civil: 's', 'c', 'v', 'd';

f = False
v = True

while v:
    nome = str(input("Coloque seu nome:"))
    idade = int(input("Coloque sua idade:"))
    salario = float (input("Coloque seu salário:"))
    sexo = str(input("Coloque seu sexo OBS: Coloque f para feminino e m para masculino:"))
    estado_civil = str(input("Coloque seu estado civil [s,c,v,d]:"))

    if len(nome) <= 3  and idade <= 0 or idade > 150 and salario <= 0 and sexo != "f" or sexo != "m" and estado_civil not in ('s, c, v, d'):
      f = False
      print("Erro")

    elif len(nome) > 3 and idade > 0 or idade < 150 and salario > 0 and sexo == "f" or sexo == "m" and estado_civil in ('s, c, v, d'):
      v = True
      print("Certo")
      break

#Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000
#habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse
#ou iguale a população do país B, mantidas as taxas de crescimento.

paisA= 80000
paisB = 200000
ano = 0

while paisB >= paisA:
  paisA += paisA * 0.03
  paisB += paisB * 0.15
  ano += 1

print(f"A quantidade de anos é: {ano}")

#Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120

numero = int(input("Coloque um número"))
fatorial = 1

for i in range(1, numero + 1):
  fatorial*= i
print(f"O fatorial desse número é: {fatorial}")

#Faça um programa que solicite ao usuário números indefinidamente até que ele digite 0. Em seguida, o programa deve imprimir a média dos números digitados.

soma = 0
quantidade = 0

while True:
  numero = float(input("Coloque um número qualquer e coloque 0 para sair: "))
  if numero == 0:
    break
    soma += numero
    quantidade += 1

if quantidade > 0:
    media = soma / quantidade
    print(f"A média é de: {media}")

else:
  print(f"Nenhum número foi digitado")

#A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o n−ésimo termo.

n_numeros = 50
contador = 0
primeiro = 1
segundo = 1
soma = 0

while contador <n_numeros:
  print(primeiro)
  soma = primeiro + segundo
  primeiro = segundo
  segundo = soma
  contador += 1

#O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e agora possui uma loja de conveniências. Faça um programa que implemente uma caixa registradora rudimentar.
# O programa deverá receber um número desconhecido de valores referentes aos preços das mercadorias. Um valor zero deve ser informado pelo operador para indicar o final da compra.
# O programa deve então mostrar o total da compra e perguntar o valor em dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
#troco. Após esta operação, o programa deverá voltar ao ponto inicial, para registrar a próxima compra.
# A saída deve ser conforme o exemplo abaixo:
# Lojas Tabajara
# Produto 1: R$ 2.20
# Produto 2: R$ 5.80
# Produto 3: R$ 0
# Total: R$ 9.00
# Dinheiro: R$ 20.00
# Troco: R$ 11.00

numero = float(input("Coloque o preço do seu produto:"))
soma = 0

while numero > 0:
  soma += numero
  numero = float(input("Coloque o preço do seu produto:"))
  if numero == 0:
    print(f"O total é", soma)

while dinheiro:
  dinheiro = float(input("Coloque seu dinheiro:"))
  dinheiro -= soma
  print(f"Seu troco é:", dinheiro)
  break

#O cardápio de uma lanchonete é o seguinte:
#Especificação Código Preço
# Cachorro Quente 100 R$ 1,20
# Bauru Simples 101 R$ 1,30
# Bauru com ovo 102 R$ 1,50
# Hambúrguer 103 R$ 1,20
# Cheeseburguer 104 R$ 1,30
# Refrigerante 105 R$ 1,00
#Faça um programa que leia o código dos itens pedidos e as quantidades desejadas. Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
#pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.

print("Códigos: Cachorro Quente = c100 / Bauru Simples = b101 / Bauru com ovo = b102 / Hambúrguer = h103 / Cheeseburguer = c104 / Refrigerante = r105")
codigo = str(input("Coloque o código dos itens:"))
quantidade = int(input("Coloque a quantidade:"))

soma = 0

while True:
  codigo = input("Coloque o código dos itens (ou '0' para encerrar o pedido):")
  if codigo == '0':
   break

   quantidade = int(input("Coloque a quantidade:"))

  if codigo == "c100":
   preco = quantidade * 1.20
   print(preco)

  elif codigo == "b101":
   preco = quantidade * 1.30
   print(preco)

  elif codigo == "b102":
    preco = quantidade * 1.50
    print(preco)

  elif codigo == "h103":
    preco = quantidade * 1.20
    print(preco)

  elif codigo == "c104":
    preco = quantidade * 1.30
    print(preco)

  elif codigo == "r105":
    preco = quantidade * 1.00
    print(preco)

  else:
    print("Código inválido")
    continue

  print(f"Preço a ser pago: R$ {preco:.2f}")
  soma+= preco

  print(f"Total a ser pago: R$ {soma:.2f}")

#O cardápio de uma lanchonete é o seguinte:
#Especificação Código Preço
# Cachorro Quente 100 R$ 1,20
# Bauru Simples 101 R$ 1,30
# Bauru com ovo 102 R$ 1,50
# Hambúrguer 103 R$ 1,20
# Cheeseburguer 104 R$ 1,30
# Refrigerante 105 R$ 1,00
#Faça um programa que leia o código dos itens pedidos e as quantidades desejadas. Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
#pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.

quantidade_produto_100 = 0
quantidade_produto_101 = 0
quantidade_produto_102 = 0
quantidade_produto_103 = 0
quantidade_produto_104 = 0
quantidade_produto_105 = 0
total = 0
print("""
    Produto         Codigo  Preco
    ------------------------------
    Cachorro Quente  100   R$ 1.20
    Bauru Simples    101   R$ 1.30
    Bauru com Ovo    102   R$ 1.50
    Hamburguer       103   R$ 1.20
    Cheeseburguer    104   R$ 1.30
    Refrigerante     105   R4 1.00
  """
)

while True:
  codigo = int(input("Digite o código do produto que deseja adquirir (ou 0 para encerrar): "))
  if codigo == 0:
    break
  if codigo > 105 or codigo < 100:
    print("Código Inválido!!")
    continue

quantidade = int(input("Digite a quantidade desse produto: "))
if codigo == 100:
  quantidade_produto_100 += quantidade

if codigo == 101:
  quantidade_produto_101 += quantidade

if codigo == 102:
  quantidade_produto_102 += quantidade

if codigo == 103:
  quantidade_produto_103 += quantidade

if codigo == 104:
  quantidade_produto_104 += quantidade

if codigo == 105:
  quantidade_produto_105 += quantidade
print("""
      Fechamento do pedido
      Codigo - Quantidade - Preço unidade - Preço Total
""")
if quantidade_produto_100 > 0:
  print(f"""
    100   -   {quantidade_produto_100}  -   R$1.20    - {quantidade_produto_100 * 1.3:.2f}
  """)
  total += quantidade_produto_100 * 1.20

if quantidade_produto_101 > 0:
  print(f"""
    101   -   {quantidade_produto_100}  -   R$1.30    - {quantidade_produto_101 * 1.3:.2f}
  """)
  total += quantidade_produto_101 * 1.30

if quantidade_produto_102 > 0:
  print(f"""
    102   -   {quantidade_produto_102}  -   R$1.50    - {quantidade_produto_102 * 1.3:.2f}
  """)
  total += quantidade_produto_102 * 1.50

if quantidade_produto_103 > 0:
  print(f"""
    103   -   {quantidade_produto_103}  -   R$1.20    - {quantidade_produto_103 * 1.3:.2f}
  """)
  total += quantidade_produto_103 * 1.20

if quantidade_produto_104 > 0:
  print(f"""
    104   -   {quantidade_produto_104}  -   R$1.30    - {quantidade_produto_104 * 1.3:.2f}
  """)
  total += quantidade_produto_104 * 1.30

if quantidade_produto_105 > 0:
  print(f"""
    105   -   {quantidade_produto_105}  -   R$1.00    - {quantidade_produto_105 * 1.3:.2f}
  """)
  total += quantidade_produto_104 * 1.00

print(f"Total do pedido: R$ {total:.2f}")

#Em uma eleição presidencial existem quatro candidatos. Os votos são informados por meio de código. Os códigos utilizados são:
# 1, 2, 3, 4 - Votos para os respectivos candidatos
# (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
# 5 - Voto Nulo
# 6 - Voto em Branco
#Faça um programa que calcule e mostre:
# O total de votos para cada candidato;
# O total de votos nulos;
# O total de votos em branco;
# A percentagem de votos nulos sobre o total de votos;
# A percentagem de votos em branco sobre o total de votos.
#Para finalizar o conjunto de votos tem-se o valor zero.

print("Candidatos: \n1 - José\n2 - João\n3 - Maria\n4 - Clara")
print("Digite 0 para sair, 5 para votar nulo ou 6 para votar em branco.")
votos = 0
candidato_1 = 0

candidato_2 = 0
candidato_3 = 0
candidato_4 = 0
nulos = 0
brancos = 0
while True:
  voto = int(input(f"Digite o voto numero {votos + 1}: "))
  if voto == 0:
    break
  votos += 1
  if voto == 1:
    candidato_1 += 1
  elif voto == 2:
    candidato_2 += 1
  elif voto == 3:
    candidato_3 += 1
  elif voto == 4:
    candidato_4 += 1
  elif voto == 5:
    nulos += 1
  elif voto == 6:
    brancos += 1
  else:
    print("Voto inválido!")
    votos -= 1
print(
  "\nResultado da eleição:"
  f"\nJosé teve {candidato_1} votos"
  f"\nJoão teve {candidato_2} votos"
  f"\nMaria teve {candidato_3} votos"
  f"\nClara teve {candidato_4} votos"
  f"\n{nulos} votos foram anulados, um total de {100 * nulos / votos:.2f}%"
  f"\n{brancos} votos foram em branco, um total de {100 * brancos / votos:.2f}%"
)